version: "3.9"
services:
  app:   
    build:
      context: .
      dockerfile: Dockerfile
    container_name: waymore-app
    stdin_open: true
    tty: true
    volumes:
      - ./results:/app/results
